### ISSUE TITLE
NOT AN ISSUE, BUT A REQUEST

### ISSUE THREAD

**Issue by harsharora08** [BlafKing/spicetify-cat-jam-synced#1]
I absolutely adore this extension.
I was wondering if you could make one for a gif that I have. If you have time to spare and if you want to, of course.

I tried reading the code and adding the gif (webm converted) myself but I guess there is more to it than just that.

Anyway, here is the gif I am talking about 

![this gif](https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExcWdwaTA1OTVtcGJlczhxcWVpaWZsYjc2ank1c3hpcmFvcW03N3BqZCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/27w13QSPXeMYnHcw2g/giphy.gif)

Thanks in advance
<3

**Comment by ohitstom** [comment]
a custom image / gif settings menu would be nice - even if the user is forced to define the default BPM values or any other needed data

**Comment by Satanarious** [comment]
> a custom image / gif settings menu would be nice - even if the user is forced to define the default BPM values or any other needed data

This would be perfect.

**Comment by BlafKing** [comment]
> a custom image / gif settings menu would be nice - even if the user is forced to define the default BPM values or any other needed data

Sounds good!
I'll look into how I can add settings somewhere where you can define a custom webm and default BPM of that webm! :)

**Comment by BlafKing** [comment]
Latest commit now includes some setting in the Spotify settings tab where you can define a custom webM link and a default BPM for the webM that you're using!

![image](https://github.com/BlafKing/spicetify-cat-jam-synced/assets/9644716/df6358fa-6e9e-496f-a8a8-1801ac0f92a9)
(Reload button look a little bad but, at least it works😅)

I'll close this request as it should be solved! 👍🏻 
Please do feel free to ask any more questions related to the custom webM's here though!

**Comment by Satanarious** [comment]
Any plans on supporting a local path to the WebM file?

**Comment by BlafKing** [comment]
> Any plans on supporting a local path to the WebM file?

I'd definitely like to see if that's possible, but it's always a bit tricky when making something with just typescript/javascript, since it does not have the ability to access and or modify local files directly.

I'll see if I can find a workaround and if any else knows a good way to achieve this, feel free to let me know!

**Comment by Satanarious** [comment]
Maybe you can store the location in `local storage` as few themes do. And any changes in the location or URL will make changes in the variable in the `local storage`.

**Comment by ohitstom** [comment]
> > Any plans on supporting a local path to the WebM file?
> 
> I'd definitely like to see if that's possible, but it's always a bit tricky when making something with just typescript/javascript, since it does not have the ability to access and or modify local files directly.
> 
> I'll see if I can find a workaround and if any else knows a good way to achieve this, feel free to let me know!

one thing the user can do is place it in an assets folder in their theme but this doesn't work with marketplace, essentially aslong as the image is in your xpui folder Spotify can access it

**Comment by doot-64** [comment]
> Latest commit now includes some settings in the Spotify settings tab where you can define a custom webM link and a default BPM for the webM that you're using!
> 
> ![image](https://private-user-images.githubusercontent.com/9644716/320157395-df6358fa-6e9e-496f-a8a8-1801ac0f92a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2ODIyNzgsIm5iZiI6MTcxMjY4MTk3OCwicGF0aCI6Ii85NjQ0NzE2LzMyMDE1NzM5NS1kZjYzNThmYS02ZTllLTQ5NmYtYThhOC0xODAxYWMwZjkyYTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMTY1OTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTI4MDQ4ZjQ5ZjIwYmMwOWFkODBkYWY2OWZiOWMxZDg1NWU3MzEwODFkNTUzMDA3YmUzZDU5NTcxYzhmMWY4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.a9oo61EF1HjZTgchYmE79DT6dbDsS3UaLxyPWUVkL28) (Reload button look a little bad but, at least it works😅)
> 
> I'll close this request as it should be solved! 👍🏻 Please do feel free to ask any more questions related to the custom webM's here though!

Are there specific requirements for the webm link to work? None of my tries with my hosted webm videos worked so far. Am I missing something?
