### ISSUE TITLE
Add where to find cat-jam-synced settings in the readme

### ISSUE THREAD

**Issue by picklepopper1** [BlafKing/spicetify-cat-jam-synced#12]
This might be common knowledge, but I think it'd be really valuable to new users to state where to find the settings for this extension. I didn't even know it had settings until today.

I also wanted to take the time to thank you for your extension. I think it's my favorite one!

**Comment by tojatomasz** [comment]
@picklepopper1 
This might be common knowledge, but i wasn't able to find the settings page.
Could you help me, and other that would end here, how we can find it? :D

**Comment by picklepopper1** [comment]
> @picklepopper1 This might be common knowledge, but i wasn't able to find the settings page. Could you help me, and other that would end here, how we can find it? :D

Yes! It is in the regular Spotify settings page all the way at the bottom. If you need help finding the Spotify client settings, just [click here](https://community.spotify.com/t5/App-Features/Where-are-the-settings-in-the-new-desktop-interface/td-p/5571705#:~:text=Hi%20%40mtilsted-,You%20can%20access%20the%20settings%20page%20via%20the%20menu%20under,meatball%20menu%20under%20Edit%20%3E%20Preferences.).
