### ISSUE TITLE
not an issue but a help needed.

### ISSUE THREAD

**Issue by rahulchaudhari06** [BlafKing/spicetify-cat-jam-synced#13]
Can you provide a way tp increase the size of the cat-jam?
its okay even if you tell to modify some code :)

**Comment by rahulchaudhari06** [comment]
> Can you provide a way tp increase the size of the cat-jam? its okay even if you tell to modify some code :)

i tried increeasing the height , width and maxheight from the code but didnt work

**Comment by mountaincastle47** [comment]
man have you find out how to do that
